### ISSUE TITLE
Import project

### ISSUE THREAD

**Issue by FabioGenesy** [evandro-teixeira/FreeModbus_KL25Z#1]
Hi Evandro,
for which IDE is developed this project?
I tried to import it on MCUXpresso but is incompatible.

Thank you very much!
Fabio

**Comment by evandro-teixeira** [comment]
Hi Fabio,
The IDE used in the project is KDS.
To use MCUXpresso it would be necessary to create a new project and add to my implementation.
Note: MCUXpresso SDK is not used in this project, it is a library that I developed myself
https://github.com/evandro-teixeira/Library-FRDM-KL25Z/tree/849de45b39cc3afafb62873090416a89727bcb99
